services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    # image: react-flask-app-api
    depends_on:
      - postgres_mun
    ports:
      - "5003:5003"
    links:
      - postgres_mun:postgres_mun
    networks:
      - backend_mun
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - backend
    ports:
      - "3004:80"
    links:
      - backend:backend
    networks:
      - backend_mun
  postgres_mun:
    container_name: postgres_mun
    image: postgres:latest
    ports:
      - "5431:5432"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    
    expose:
      - "5432"
    networks:
      - backend_mun
networks:
  backend_mun:
    driver: bridge